image: docker.phonepe.com:5000/pp-maven:3.6.3-openjdk-8-slim

.default: &default
  only:
    - merge_requests
    - web

.default_tag: &default_tag
  tags:
    - backend

stages:
  - build
  - quality
  - deploy
  - merge
  - release

"Build Snapshot":
  stage: build
  <<: *default
  <<: *default_tag
  script:
    - mvn package -U -DskipTests=true -Denforcer.skip

"Merge Ready":
  stage: quality
  <<: *default
  <<: *default_tag
  script:
    - mvn verify -U -Psirius -Pquality_check -Dsonar.pullrequest.key=$CI_MERGE_REQUEST_IID -Dsonar.pullrequest.branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME -Dsonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME

"Deploy Snapshot":
  stage: deploy
  <<: *default_tag
  <<: *default
  allow_failure: false
  script:
    - mvn deploy -U -DskipTests=true -Denforcer.skip
  when: manual

"Release":
  <<: *default_tag
  stage: release
  script:
    - git remote set-url origin "git@gitlab.phonepe.com:${CI_PROJECT_PATH}.git"
    - git checkout master
    - git pull origin master
    - git checkout develop
    - git pull origin develop
    - mvn -U jgitflow:release-start jgitflow:release-finish
    - git push --all
    - git push --tags origin
  when: manual
  only:
    refs:
      - develop
